"""'Change test_items column type from JSON to String'

Revision ID: 3d646381c488
Revises: 975d31d71708
Create Date: 2025-08-17 17:08:27.856555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '3d646381c488'
down_revision = '975d31d71708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_reports', schema=None) as batch_op:
        batch_op.alter_column('test_items',
               existing_type=sqlite.JSON(),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_reports', schema=None) as batch_op:
        batch_op.alter_column('test_items',
               existing_type=sa.String(length=500),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
