"""Correct registrant field nullable setting

Revision ID: 487cbbeca383
Revises: fdafcc58b834
Create Date: 2025-08-21 00:04:38.141785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487cbbeca383'
down_revision = 'fdafcc58b834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 跳过添加created_by_nickname列，该列已存在
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    inspection_columns = [c['name'] for c in inspector.get_columns('inspection_reports')]

    with op.batch_alter_table('inspection_reports', schema=None) as batch_op:
        if 'registrant_id' not in inspection_columns:
            batch_op.add_column(sa.Column('registrant_id', sa.Integer(), nullable=True, comment='登记人ID'))
        if 'last_modified_by_id' not in inspection_columns:
            batch_op.add_column(sa.Column('last_modified_by_id', sa.Integer(), nullable=True, comment='最后修改人ID'))
        if 'last_modified_by_id' in inspection_columns:
            batch_op.create_foreign_key('fk_inspection_reports_last_modified_by_id', 'users', ['last_modified_by_id'], ['id'])
        if 'registrant_id' in inspection_columns:
            batch_op.create_foreign_key('fk_inspection_reports_registrant_id', 'users', ['registrant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查并删除inspection_reports表的列和约束（如果存在）
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    inspection_columns = [c['name'] for c in inspector.get_columns('inspection_reports')]
    inspection_constraints = [c['name'] for c in inspector.get_constraints('inspection_reports')]

    with op.batch_alter_table('inspection_reports', schema=None) as batch_op:
        if 'fk_inspection_reports_last_modified_by_id' in inspection_constraints:
            batch_op.drop_constraint('fk_inspection_reports_last_modified_by_id', type_='foreignkey')
        if 'fk_inspection_reports_registrant_id' in inspection_constraints:
            batch_op.drop_constraint('fk_inspection_reports_registrant_id', type_='foreignkey')
        if 'last_modified_by_id' in inspection_columns:
            batch_op.drop_column('last_modified_by_id')
        if 'registrant_id' in inspection_columns:
            batch_op.drop_column('registrant_id')

    # ### end Alembic commands ###
