"""Add created_by_nickname column to announcements table

Revision ID: 4fa8b40efa28
Revises: de53b64bf910
Create Date: 2025-08-21 15:59:47.907643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fa8b40efa28'
down_revision = 'de53b64bf910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_nickname', sa.String(length=50), nullable=True))

    with op.batch_alter_table('inspection_reports', schema=None) as batch_op:
        batch_op.alter_column('test_items',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='检测项详情',
               existing_nullable=True)
        batch_op.alter_column('registrant',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=50),
               comment='登记人',
               existing_nullable=True)
        batch_op.alter_column('last_modified_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='最后修改人',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_reports', schema=None) as batch_op:
        batch_op.alter_column('last_modified_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='最后修改人',
               existing_nullable=True)
        batch_op.alter_column('registrant',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='登记人',
               existing_nullable=True)
        batch_op.alter_column('test_items',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='检测项详情',
               existing_nullable=True)

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_column('created_by_nickname')

    # ### end Alembic commands ###
