"""Add is_deleted column to announcements table

Revision ID: 975d31d71708
Revises: bb858d5748c9
Create Date: 2025-08-17 16:14:13.454309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975d31d71708'
down_revision = 'bb858d5748c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
