"""Initial migration

Revision ID: bb858d5748c9
Revises: 
Create Date: 2025-08-17 15:21:36.007623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb858d5748c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False, comment='工程名称'),
    sa.Column('project_location', sa.String(length=200), nullable=True, comment='工程地址'),
    sa.Column('project_type', sa.String(length=50), nullable=True, comment='工程类型'),
    sa.Column('project_stage', sa.String(length=50), nullable=True, comment='工程阶段'),
    sa.Column('construction_unit', sa.String(length=100), nullable=True, comment='建设单位'),
    sa.Column('contractor', sa.String(length=100), nullable=True, comment='施工单位'),
    sa.Column('supervisor', sa.String(length=100), nullable=True, comment='监理单位'),
    sa.Column('witness_unit', sa.String(length=100), nullable=True, comment='见证单位'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('client_unit', sa.String(length=200), nullable=False, comment='委托单位'),
    sa.Column('client_contact', sa.String(length=50), nullable=True, comment='委托人'),
    sa.Column('acceptance_date', sa.Date(), nullable=True, comment='受理日期'),
    sa.Column('commission_date', sa.Date(), nullable=True, comment='委托日期'),
    sa.Column('commission_code', sa.String(length=100), nullable=True, comment='委托编号'),
    sa.Column('salesperson', sa.String(length=50), nullable=True, comment='业务员'),
    sa.Column('inspection_unit', sa.String(length=200), nullable=True, comment='检测单位'),
    sa.Column('certificate_no', sa.String(length=50), nullable=True, comment='资质证书编号'),
    sa.Column('contact_address', sa.String(length=200), nullable=True, comment='联系地址'),
    sa.Column('contact_phone', sa.String(length=50), nullable=True, comment='联系电话'),
    sa.Column('registrant', sa.String(length=50), nullable=True, comment='登记人'),
    sa.Column('inspection_object', sa.String(length=100), nullable=True, comment='检测对象'),
    sa.Column('object_part', sa.String(length=100), nullable=True, comment='检测部位'),
    sa.Column('object_spec', sa.String(length=100), nullable=True, comment='对象规格'),
    sa.Column('design_spec', sa.Text(), nullable=True, comment='设计要求'),
    sa.Column('inspection_type', sa.String(length=50), nullable=True, comment='检验类型'),
    sa.Column('inspection_items', sa.String(length=200), nullable=True, comment='检测项目'),
    sa.Column('test_items', sa.JSON(), nullable=True, comment='检测项详情'),
    sa.Column('inspection_quantity', sa.Integer(), nullable=True, comment='检测数量'),
    sa.Column('measurement_unit', sa.String(length=20), nullable=True, comment='计量单位'),
    sa.Column('inspection_conclusion', sa.String(length=200), nullable=True, comment='检测结论'),
    sa.Column('conclusion_description', sa.Text(), nullable=True, comment='结论描述'),
    sa.Column('is_recheck', sa.Boolean(), nullable=True, comment='是否复检'),
    sa.Column('sampling_method', sa.String(length=50), nullable=True, comment='抽样方式'),
    sa.Column('sampling_date', sa.Date(), nullable=True, comment='抽样日期'),
    sa.Column('sampler', sa.String(length=50), nullable=True, comment='抽样人员'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='开始日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='结束日期'),
    sa.Column('inspection_code', sa.String(length=50), nullable=True, comment='检测编号'),
    sa.Column('inspector', sa.String(length=50), nullable=True, comment='检测员'),
    sa.Column('tester_date', sa.Date(), nullable=True, comment='检测完成日期'),
    sa.Column('reviewer', sa.String(length=50), nullable=True, comment='审核人'),
    sa.Column('review_date', sa.Date(), nullable=True, comment='审核日期'),
    sa.Column('approver', sa.String(length=50), nullable=True, comment='批准人'),
    sa.Column('approve_date', sa.Date(), nullable=True, comment='批准日期'),
    sa.Column('report_date', sa.Date(), nullable=False, comment='报告日期'),
    sa.Column('issue_date', sa.Date(), nullable=True, comment='签发日期'),
    sa.Column('report_code', sa.String(length=100), nullable=False, comment='报告编号'),
    sa.Column('report_status', sa.String(length=20), nullable=True, comment='报告状态'),
    sa.Column('qrcode_content', sa.String(length=200), nullable=True, comment='二维码内容'),
    sa.Column('attachment_paths', sa.JSON(), nullable=True, comment='附件路径'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_code')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_logout_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('openid', sa.String(length=64), nullable=True),
    sa.Column('unionid', sa.String(length=64), nullable=True),
    sa.Column('member_level', sa.Integer(), nullable=True),
    sa.Column('ext_info', sa.JSON(), nullable=True),
    sa.Column('position_name', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.Integer(), nullable=True),
    sa.Column('hire_date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('id_card_number', sa.String(length=128), nullable=True),
    sa.Column('reset_token', sa.String(length=128), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('verification_code', sa.String(length=10), nullable=True),
    sa.Column('verification_code_expires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_title'), ['title'], unique=False)

    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('certificate_name', sa.String(length=200), nullable=False),
    sa.Column('issuing_authority', sa.String(length=200), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_user_id'), ['user_id'], unique=False)

    op.create_table('educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('education_level', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=False),
    sa.Column('major', sa.String(length=100), nullable=False),
    sa.Column('graduation_date', sa.DateTime(), nullable=False),
    sa.Column('degree_certificate_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('educations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_educations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_educations_user_id'), ['user_id'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_permissions_id'), ['id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permissions')
    op.drop_table('role_permissions')
    op.drop_table('user_roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_id'))
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    with op.batch_alter_table('educations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_educations_user_id'))
        batch_op.drop_index(batch_op.f('ix_educations_id'))

    op.drop_table('educations')
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_user_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_id'))

    op.drop_table('certificates')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_title'))
        batch_op.drop_index(batch_op.f('ix_announcements_id'))

    op.drop_table('announcements')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_id'))

    op.drop_table('roles')
    op.drop_table('inspection_reports')
    # ### end Alembic commands ###
