"""Check for any new model changes

Revision ID: de53b64bf910
Revises: 5bbb78b040da
Create Date: 2025-08-21 00:14:27.729335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de53b64bf910'
down_revision = '5bbb78b040da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_reports', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_inspection_reports_registrant_id', 'users', ['registrant_id'], ['id'])
        batch_op.create_foreign_key('fk_inspection_reports_last_modified_by_id', 'users', ['last_modified_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_reports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inspection_reports_registrant_id', type_='foreignkey')
        batch_op.drop_constraint('fk_inspection_reports_last_modified_by_id', type_='foreignkey')

    # ### end Alembic commands ###
